# Generated by Django 6.0.5 on 2026-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('params', models.TextField(default='{}')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('component', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('raw_data', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('component', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='online', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(default='Unknown', max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ports', models.TextField(default='[]')),
                ('vulns', models.TextField(default='[]')),
                ('status', models.CharField(default='Healthy', max_length=50)),
                ('score', models.IntegerField(default=100)),
            ],
        ),
    ]
